version: '2'
volumes:
    mysql_data: {}
services:
  django:
    build:
      context: ./
    image: django-polls
    command: bash run.sh
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_polls
    volumes: 
      - mysql_data:/var/lib/mysql
